# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_auth', '0002_auto_20171011_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Normal user', 'Normal user'), ('User manager', 'User manager'), ('Administrator', 'Administrator')], default='Normal user', max_length=15),
        ),
    ]
